inhook 2
tuck - f4 2
tuck - f3 2
tuck - f2 2
tuck - f1 2
tuck - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
releasehook 2
xfer f1 b1
xfer f2 b2
xfer f3 b3
rack -2
xfer b3 f1
rack 1
xfer b1 f2
xfer b2 f3
rack 0
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
xfer f1 b1
xfer f2 b2
xfer f3 b3
rack 1
xfer b1 f2
xfer b2 f3
rack -2
xfer b3 f1
rack 0
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
xfer f1 b1
xfer f2 b2
xfer f3 b3
rack -1
xfer b2 f1
xfer b3 f2
rack 2
xfer b1 f3
rack 0
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
xfer f1 b1
xfer f2 b2
xfer f3 b3
rack 2
xfer b1 f3
rack -1
xfer b2 f1
xfer b3 f2
rack 0
knit - f4 2
knit - f3 2
knit - f2 2
knit - f1 2
knit - f0 2
knit + f0 2
knit + f1 2
knit + f2 2
knit + f3 2
knit + f4 2
outhook 2